import { useMemo } from "react";
import { useMyAttendance } from "@/features/school/queries";
import { useMyRegistrationCards, type MyRegistration } from "@/features/school/my-registrations";
import { useNotifications } from "@/features/school/notifications";
import {
  occurrencesForGroups,
  toIsoDate,
  type SessionOccurrence,
} from "@/features/school/schedule";
import type { AttendanceStatus, GroupRow } from "@/features/school/types";

/** How far ahead the portal looks. Bounded so no page expands a whole year. */
const HORIZON_DAYS = 60;

/**
 * Adapts a registration into the shape the occurrence engine expects.
 *
 * The engine is defined over `GroupRow`; registrations carry the same group
 * facts under different names. Converting here keeps recurrence logic in
 * `schedule.ts` alone -- this is a rename, not a second implementation.
 */
function toGroupRow(r: MyRegistration): GroupRow {
  return {
    id: r.groupId,
    name: r.groupName,
    subjectId: null,
    subjectKey: r.subjectKey,
    subjectName: r.subjectName,
    subjectColor: r.subjectColor,
    teacherId: null,
    teacherName: r.teacherName,
    levelId: null,
    levelName: r.levelName,
    streamId: null,
    startDate: r.startDate,
    endDate: r.endDate,
    maxStudents: 0,
    priceDzd: r.priceDzd,
    status: "active",
    enrolled: 0,
    schedules: r.schedules,
  };
}

/**
 * Everything the student portal needs, derived once.
 *
 * Dashboard, My Classes, Schedule and Attendance all read from here rather than
 * each assembling their own timetable and totals. Since the scheduling engine
 * landed, "my week" means **real dated occurrences** clamped to each group's
 * term -- not a timeless weekday pattern. A group whose end_date has passed
 * simply produces nothing, so ended courses disappear everywhere at once.
 */
export function useStudentPortal(studentId: string | undefined) {
  const registrationsQuery = useMyRegistrationCards(studentId);
  const attendanceQuery = useMyAttendance(studentId);
  const notificationsQuery = useNotifications(studentId);

  const registrations = registrationsQuery.items;

  /** Only approved registrations are real classes -- pending ones are requests. */
  const enrolled = useMemo<MyRegistration[]>(
    () => registrations.filter((r) => r.status === "approved" && !r.groupUnavailable),
    [registrations],
  );

  const pending = useMemo(
    () => registrations.filter((r) => r.status === "pending"),
    [registrations],
  );

  const today = new Date();
  const todayIso = toIsoDate(today);
  const todayWeekday = today.getDay();

  /**
   * Real dated sessions across the horizon, generated by the shared engine.
   * Ended groups contribute nothing; open-ended ones are capped by the engine.
   */
  const occurrences = useMemo<SessionOccurrence[]>(() => {
    const groups = enrolled.map(toGroupRow);
    const to = new Date(today.getTime() + HORIZON_DAYS * 86_400_000);
    return occurrencesForGroups(groups, { from: todayIso, to: toIsoDate(to) });
    // `todayIso` is the stable input; `today` is a fresh Date each render.
  }, [enrolled, todayIso]);

  /** Sessions dated today -- never inferred from a weekday match. */
  const todayOccurrences = useMemo(
    () => occurrences.filter((o) => o.date === todayIso),
    [occurrences, todayIso],
  );

  /** The next session that has not started yet, or null once a course ends. */
  const nextOccurrence = useMemo(
    () => occurrences.find((o) => o.startsAt >= today) ?? null,
    [occurrences, todayIso],
  );

  /** Next session per group, for the My Classes cards. */
  const nextByGroup = useMemo(() => {
    const map = new Map<string, SessionOccurrence>();
    for (const o of occurrences) {
      if (o.startsAt < today) continue;
      if (!map.has(o.group.id)) map.set(o.group.id, o);
    }
    return map;
  }, [occurrences, todayIso]);

  const attendance = attendanceQuery.data ?? [];
  const attendanceSummary = useMemo(() => {
    const statuses = attendance.map((a) => a.status as AttendanceStatus);
    const present = statuses.filter((s) => s === "present").length;
    const late = statuses.filter((s) => s === "late").length;
    const excused = statuses.filter((s) => s === "excused").length;
    const absent = statuses.filter((s) => s === "absent").length;
    const total = statuses.length;
    return {
      total,
      present,
      late,
      excused,
      absent,
      // Late still counts as attended -- the student was in the room.
      rate: total > 0 ? Math.round(((present + late) / total) * 100) : 0,
    };
  }, [attendance]);

  const unreadNotifications = (notificationsQuery.data ?? []).filter((n) => !n.readAt).length;

  return {
    registrations,
    enrolled,
    pending,
    occurrences,
    todayOccurrences,
    nextOccurrence,
    nextByGroup,
    attendance,
    attendanceSummary,
    unreadNotifications,
    todayWeekday,
    isLoading: registrationsQuery.isLoading || attendanceQuery.isLoading,
    isFetching: registrationsQuery.isFetching || attendanceQuery.isFetching,
    error: registrationsQuery.error ?? attendanceQuery.error,
    refetch: () => {
      registrationsQuery.refetch();
      void attendanceQuery.refetch();
    },
  };
}
