/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as DashboardAttendanceReportRouteImport } from './routes/dashboard.attendance-report'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard.groups'
import { Route as DashboardLevelsRouteImport } from './routes/dashboard.levels'
import { Route as DashboardMyAttendanceRouteImport } from './routes/dashboard.my-attendance'
import { Route as DashboardMyClassesRouteImport } from './routes/dashboard.my-classes'
import { Route as DashboardMyGroupsRouteImport } from './routes/dashboard.my-groups'
import { Route as DashboardMyRegistrationsRouteImport } from './routes/dashboard.my-registrations'
import { Route as DashboardMyStudentsRouteImport } from './routes/dashboard.my-students'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardRegistrationRouteImport } from './routes/dashboard.registration'
import { Route as DashboardRegistrationsRouteImport } from './routes/dashboard.registrations'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard.schedule'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSubjectsRouteImport } from './routes/dashboard.subjects'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardTeachersRouteImport } from './routes/dashboard.teachers'
import { Route as DashboardGroupsGroupIdRouteImport } from './routes/dashboard.groups.$groupId'
import { Route as DashboardStudentsStudentIdRouteImport } from './routes/dashboard.students.$studentId'
import { Route as DashboardTeachersTeacherIdRouteImport } from './routes/dashboard.teachers.$teacherId'
import { Route as DashboardRegistrationSuccessRegistrationIdRouteImport } from './routes/dashboard.registration.success.$registrationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceReportRoute =
  DashboardAttendanceReportRouteImport.update({
    id: '/attendance-report',
    path: '/attendance-report',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLevelsRoute = DashboardLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyAttendanceRoute = DashboardMyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyClassesRoute = DashboardMyClassesRouteImport.update({
  id: '/my-classes',
  path: '/my-classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyGroupsRoute = DashboardMyGroupsRouteImport.update({
  id: '/my-groups',
  path: '/my-groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyRegistrationsRoute =
  DashboardMyRegistrationsRouteImport.update({
    id: '/my-registrations',
    path: '/my-registrations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMyStudentsRoute = DashboardMyStudentsRouteImport.update({
  id: '/my-students',
  path: '/my-students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationRoute = DashboardRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrationsRoute = DashboardRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubjectsRoute = DashboardSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachersRoute = DashboardTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsGroupIdRoute = DashboardGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => DashboardGroupsRoute,
} as any)
const DashboardStudentsStudentIdRoute =
  DashboardStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => DashboardStudentsRoute,
  } as any)
const DashboardTeachersTeacherIdRoute =
  DashboardTeachersTeacherIdRouteImport.update({
    id: '/$teacherId',
    path: '/$teacherId',
    getParentRoute: () => DashboardTeachersRoute,
  } as any)
const DashboardRegistrationSuccessRegistrationIdRoute =
  DashboardRegistrationSuccessRegistrationIdRouteImport.update({
    id: '/success/$registrationId',
    path: '/success/$registrationId',
    getParentRoute: () => DashboardRegistrationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/attendance-report': typeof DashboardAttendanceReportRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/levels': typeof DashboardLevelsRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-classes': typeof DashboardMyClassesRoute
  '/dashboard/my-groups': typeof DashboardMyGroupsRoute
  '/dashboard/my-registrations': typeof DashboardMyRegistrationsRoute
  '/dashboard/my-students': typeof DashboardMyStudentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registration': typeof DashboardRegistrationRouteWithChildren
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/teachers': typeof DashboardTeachersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/groups/$groupId': typeof DashboardGroupsGroupIdRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/teachers/$teacherId': typeof DashboardTeachersTeacherIdRoute
  '/dashboard/registration/success/$registrationId': typeof DashboardRegistrationSuccessRegistrationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/attendance-report': typeof DashboardAttendanceReportRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/levels': typeof DashboardLevelsRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-classes': typeof DashboardMyClassesRoute
  '/dashboard/my-groups': typeof DashboardMyGroupsRoute
  '/dashboard/my-registrations': typeof DashboardMyRegistrationsRoute
  '/dashboard/my-students': typeof DashboardMyStudentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registration': typeof DashboardRegistrationRouteWithChildren
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/teachers': typeof DashboardTeachersRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/groups/$groupId': typeof DashboardGroupsGroupIdRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/teachers/$teacherId': typeof DashboardTeachersTeacherIdRoute
  '/dashboard/registration/success/$registrationId': typeof DashboardRegistrationSuccessRegistrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/attendance-report': typeof DashboardAttendanceReportRoute
  '/dashboard/groups': typeof DashboardGroupsRouteWithChildren
  '/dashboard/levels': typeof DashboardLevelsRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-classes': typeof DashboardMyClassesRoute
  '/dashboard/my-groups': typeof DashboardMyGroupsRoute
  '/dashboard/my-registrations': typeof DashboardMyRegistrationsRoute
  '/dashboard/my-students': typeof DashboardMyStudentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registration': typeof DashboardRegistrationRouteWithChildren
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRouteWithChildren
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/teachers': typeof DashboardTeachersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/groups/$groupId': typeof DashboardGroupsGroupIdRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/teachers/$teacherId': typeof DashboardTeachersTeacherIdRoute
  '/dashboard/registration/success/$registrationId': typeof DashboardRegistrationSuccessRegistrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard/attendance'
    | '/dashboard/attendance-report'
    | '/dashboard/groups'
    | '/dashboard/levels'
    | '/dashboard/my-attendance'
    | '/dashboard/my-classes'
    | '/dashboard/my-groups'
    | '/dashboard/my-registrations'
    | '/dashboard/my-students'
    | '/dashboard/profile'
    | '/dashboard/registration'
    | '/dashboard/registrations'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teacher'
    | '/dashboard/teachers'
    | '/dashboard/'
    | '/dashboard/groups/$groupId'
    | '/dashboard/students/$studentId'
    | '/dashboard/teachers/$teacherId'
    | '/dashboard/registration/success/$registrationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard/attendance'
    | '/dashboard/attendance-report'
    | '/dashboard/groups'
    | '/dashboard/levels'
    | '/dashboard/my-attendance'
    | '/dashboard/my-classes'
    | '/dashboard/my-groups'
    | '/dashboard/my-registrations'
    | '/dashboard/my-students'
    | '/dashboard/profile'
    | '/dashboard/registration'
    | '/dashboard/registrations'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teacher'
    | '/dashboard/teachers'
    | '/dashboard'
    | '/dashboard/groups/$groupId'
    | '/dashboard/students/$studentId'
    | '/dashboard/teachers/$teacherId'
    | '/dashboard/registration/success/$registrationId'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard/attendance'
    | '/dashboard/attendance-report'
    | '/dashboard/groups'
    | '/dashboard/levels'
    | '/dashboard/my-attendance'
    | '/dashboard/my-classes'
    | '/dashboard/my-groups'
    | '/dashboard/my-registrations'
    | '/dashboard/my-students'
    | '/dashboard/profile'
    | '/dashboard/registration'
    | '/dashboard/registrations'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/teacher'
    | '/dashboard/teachers'
    | '/dashboard/'
    | '/dashboard/groups/$groupId'
    | '/dashboard/students/$studentId'
    | '/dashboard/teachers/$teacherId'
    | '/dashboard/registration/success/$registrationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance-report': {
      id: '/dashboard/attendance-report'
      path: '/attendance-report'
      fullPath: '/dashboard/attendance-report'
      preLoaderRoute: typeof DashboardAttendanceReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/levels': {
      id: '/dashboard/levels'
      path: '/levels'
      fullPath: '/dashboard/levels'
      preLoaderRoute: typeof DashboardLevelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-attendance': {
      id: '/dashboard/my-attendance'
      path: '/my-attendance'
      fullPath: '/dashboard/my-attendance'
      preLoaderRoute: typeof DashboardMyAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-classes': {
      id: '/dashboard/my-classes'
      path: '/my-classes'
      fullPath: '/dashboard/my-classes'
      preLoaderRoute: typeof DashboardMyClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-groups': {
      id: '/dashboard/my-groups'
      path: '/my-groups'
      fullPath: '/dashboard/my-groups'
      preLoaderRoute: typeof DashboardMyGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-registrations': {
      id: '/dashboard/my-registrations'
      path: '/my-registrations'
      fullPath: '/dashboard/my-registrations'
      preLoaderRoute: typeof DashboardMyRegistrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-students': {
      id: '/dashboard/my-students'
      path: '/my-students'
      fullPath: '/dashboard/my-students'
      preLoaderRoute: typeof DashboardMyStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registration': {
      id: '/dashboard/registration'
      path: '/registration'
      fullPath: '/dashboard/registration'
      preLoaderRoute: typeof DashboardRegistrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registrations': {
      id: '/dashboard/registrations'
      path: '/registrations'
      fullPath: '/dashboard/registrations'
      preLoaderRoute: typeof DashboardRegistrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subjects': {
      id: '/dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof DashboardSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teachers': {
      id: '/dashboard/teachers'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof DashboardTeachersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/$groupId': {
      id: '/dashboard/groups/$groupId'
      path: '/$groupId'
      fullPath: '/dashboard/groups/$groupId'
      preLoaderRoute: typeof DashboardGroupsGroupIdRouteImport
      parentRoute: typeof DashboardGroupsRoute
    }
    '/dashboard/students/$studentId': {
      id: '/dashboard/students/$studentId'
      path: '/$studentId'
      fullPath: '/dashboard/students/$studentId'
      preLoaderRoute: typeof DashboardStudentsStudentIdRouteImport
      parentRoute: typeof DashboardStudentsRoute
    }
    '/dashboard/teachers/$teacherId': {
      id: '/dashboard/teachers/$teacherId'
      path: '/$teacherId'
      fullPath: '/dashboard/teachers/$teacherId'
      preLoaderRoute: typeof DashboardTeachersTeacherIdRouteImport
      parentRoute: typeof DashboardTeachersRoute
    }
    '/dashboard/registration/success/$registrationId': {
      id: '/dashboard/registration/success/$registrationId'
      path: '/success/$registrationId'
      fullPath: '/dashboard/registration/success/$registrationId'
      preLoaderRoute: typeof DashboardRegistrationSuccessRegistrationIdRouteImport
      parentRoute: typeof DashboardRegistrationRoute
    }
  }
}

interface DashboardGroupsRouteChildren {
  DashboardGroupsGroupIdRoute: typeof DashboardGroupsGroupIdRoute
}

const DashboardGroupsRouteChildren: DashboardGroupsRouteChildren = {
  DashboardGroupsGroupIdRoute: DashboardGroupsGroupIdRoute,
}

const DashboardGroupsRouteWithChildren = DashboardGroupsRoute._addFileChildren(
  DashboardGroupsRouteChildren,
)

interface DashboardRegistrationRouteChildren {
  DashboardRegistrationSuccessRegistrationIdRoute: typeof DashboardRegistrationSuccessRegistrationIdRoute
}

const DashboardRegistrationRouteChildren: DashboardRegistrationRouteChildren = {
  DashboardRegistrationSuccessRegistrationIdRoute:
    DashboardRegistrationSuccessRegistrationIdRoute,
}

const DashboardRegistrationRouteWithChildren =
  DashboardRegistrationRoute._addFileChildren(
    DashboardRegistrationRouteChildren,
  )

interface DashboardStudentsRouteChildren {
  DashboardStudentsStudentIdRoute: typeof DashboardStudentsStudentIdRoute
}

const DashboardStudentsRouteChildren: DashboardStudentsRouteChildren = {
  DashboardStudentsStudentIdRoute: DashboardStudentsStudentIdRoute,
}

const DashboardStudentsRouteWithChildren =
  DashboardStudentsRoute._addFileChildren(DashboardStudentsRouteChildren)

interface DashboardTeachersRouteChildren {
  DashboardTeachersTeacherIdRoute: typeof DashboardTeachersTeacherIdRoute
}

const DashboardTeachersRouteChildren: DashboardTeachersRouteChildren = {
  DashboardTeachersTeacherIdRoute: DashboardTeachersTeacherIdRoute,
}

const DashboardTeachersRouteWithChildren =
  DashboardTeachersRoute._addFileChildren(DashboardTeachersRouteChildren)

interface DashboardRouteChildren {
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardAttendanceReportRoute: typeof DashboardAttendanceReportRoute
  DashboardGroupsRoute: typeof DashboardGroupsRouteWithChildren
  DashboardLevelsRoute: typeof DashboardLevelsRoute
  DashboardMyAttendanceRoute: typeof DashboardMyAttendanceRoute
  DashboardMyClassesRoute: typeof DashboardMyClassesRoute
  DashboardMyGroupsRoute: typeof DashboardMyGroupsRoute
  DashboardMyRegistrationsRoute: typeof DashboardMyRegistrationsRoute
  DashboardMyStudentsRoute: typeof DashboardMyStudentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRegistrationRoute: typeof DashboardRegistrationRouteWithChildren
  DashboardRegistrationsRoute: typeof DashboardRegistrationsRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStudentsRoute: typeof DashboardStudentsRouteWithChildren
  DashboardSubjectsRoute: typeof DashboardSubjectsRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  DashboardTeachersRoute: typeof DashboardTeachersRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardAttendanceReportRoute: DashboardAttendanceReportRoute,
  DashboardGroupsRoute: DashboardGroupsRouteWithChildren,
  DashboardLevelsRoute: DashboardLevelsRoute,
  DashboardMyAttendanceRoute: DashboardMyAttendanceRoute,
  DashboardMyClassesRoute: DashboardMyClassesRoute,
  DashboardMyGroupsRoute: DashboardMyGroupsRoute,
  DashboardMyRegistrationsRoute: DashboardMyRegistrationsRoute,
  DashboardMyStudentsRoute: DashboardMyStudentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRegistrationRoute: DashboardRegistrationRouteWithChildren,
  DashboardRegistrationsRoute: DashboardRegistrationsRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStudentsRoute: DashboardStudentsRouteWithChildren,
  DashboardSubjectsRoute: DashboardSubjectsRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  DashboardTeachersRoute: DashboardTeachersRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
